when: << pipeline.parameters.run-embed-workflow >>
jobs:
  - embed-init
  # Staging builds disabled - staging environment has been dropped
  - embed-build-staging:
      requires:
        - embed-init
      filters:
        branches:
          only: /^__STAGING_DISABLED__$/
  - embed-deploy-staging-cloudflare:
      context: Audius Client
      requires:
        - embed-build-staging
      filters:
        branches:
          only: /^__STAGING_DISABLED__$/
  - embed-build-production:
      requires:
        - embed-init
      filters:
        branches:
          only: /(^release.*)$/
  - embed-deploy-production-cloudflare:
      context: Audius Client
      requires:
        - embed-build-production
      filters:
        branches:
          only: /(^release.*)$/
