when: << pipeline.parameters.run-web-workflow >>
jobs:
  - web-init:
      context:
        - Vercel

  # Build
  - web-build-production:
      context:
        - Vercel
      requires:
        - web-init
      filters:
        branches:
          only: /^main$/

  - web-build-ssr-production:
      context:
        - Vercel
      requires:
        - web-init
      filters:
        branches:
          only: /^main$/

  - web-check-ssr-production-bundlesize:
      context:
        - Vercel
      requires:
        - web-build-ssr-production

  - web-deploy-release-candidate:
      context: Audius Client
      requires:
        - web-init
        - web-build-production
        - web-build-ssr-production
        - web-check-ssr-production-bundlesize
      filters:
        branches:
          only: /^main$/

  # Production web deployment on main.
  - web-hold-production-main:
      type: approval
      requires:
        - web-build-production
        - web-build-ssr-production
        - web-check-ssr-production-bundlesize
      filters:
        branches:
          only: /^main$/
  - web-deploy-production-s3-main:
      context: Audius Client
      requires:
        - web-hold-production-main
      filters:
        branches:
          only: /^main$/
  - web-deploy-production-cloudflare-main:
      context:
        - Audius Client
        - slack-secrets
      requires:
        - web-hold-production-main
      filters:
        branches:
          only: /^main$/
  - web-deploy-sentry-sourcemaps-main:
      context: Audius Client
      requires:
        - web-hold-production-main
      filters:
        branches:
          only: /^main$/

  # Distribute production desktop binaries on main.
  - web-hold-dist-mac-production-main:
      type: approval
      requires:
        - web-build-production
      filters:
        branches:
          only: /^main$/
  - web-dist-mac-production-main:
      context:
        - Audius Client
        - Vercel
        - slack-secrets
      requires:
        - web-hold-dist-mac-production-main
      filters:
        branches:
          only: /^main$/
  - web-hold-dist-win-production-main:
      type: approval
      requires:
        - web-build-production
      filters:
        branches:
          only: /^main$/
  - web-dist-win-production-main:
      context:
        - Audius Client
        - Vercel
        - slack-secrets
      requires:
        - web-hold-dist-win-production-main
      filters:
        branches:
          only: /^main$/
  - web-hold-dist-linux-production-main:
      type: approval
      requires:
        - web-build-production
      filters:
        branches:
          only: /^main$/
  - web-dist-linux-production-main:
      context:
        - Audius Client
        - Vercel
        - slack-secrets
      requires:
        - web-hold-dist-linux-production-main
      filters:
        branches:
          only: /^main$/
