import { Name } from './Analytics'

/**
 * Events sent from every device. Any other event is only sent from a fixed
 * sample of devices (see getAnalyticsSampleRate).
 */
export const CORE_ANALYTICS_EVENTS: ReadonlySet<string> = new Set<string>([
  Name.CREATE_ACCOUNT_OPEN,
  Name.CREATE_ACCOUNT_COMPLETE_EMAIL,
  Name.CREATE_ACCOUNT_UPLOAD_PROFILE_PHOTO,
  Name.CREATE_ACCOUNT_UPLOAD_PROFILE_PHOTO_ERROR,
  Name.CREATE_ACCOUNT_UPLOAD_COVER_PHOTO,
  Name.CREATE_ACCOUNT_UPLOAD_COVER_PHOTO_ERROR,
  Name.CREATE_ACCOUNT_SELECT_GENRE,
  Name.CREATE_ACCOUNT_FOLLOW_ARTIST,
  Name.CREATE_ACCOUNT_ARTIST_PREVIEWED,
  Name.CREATE_ACCOUNT_COMPLETE_CREATING,
  Name.CREATE_ACCOUNT_COMPLETE_GUEST_CREATING,
  Name.CREATE_ACCOUNT_COMPLETE_GUEST_PROFILE,
  Name.CREATE_ACCOUNT_RATE_LIMIT,
  Name.CREATE_ACCOUNT_BLOCKED,
  Name.CREATE_ACCOUNT_WELCOME_MODAL,
  Name.CREATE_ACCOUNT_WELCOME_MODAL_UPLOAD_TRACK,
  Name.SIGN_IN_START,
  Name.SIGN_IN_FINISH,
  Name.SIGN_IN_WITH_INCOMPLETE_ACCOUNT,
  Name.SIGN_IN_WITH_DEACTIVATED_ACCOUNT,
  Name.AUDIUS_OAUTH_START,
  Name.AUDIUS_OAUTH_SUBMIT,
  Name.AUDIUS_OAUTH_COMPLETE,
  Name.AUDIUS_OAUTH_ERROR,
  Name.SHARE,
  Name.SHARE_TO_TWITTER,
  Name.REPOST,
  Name.UNDO_REPOST,
  Name.FAVORITE,
  Name.UNFAVORITE,
  Name.FOLLOW,
  Name.UNFOLLOW,
  Name.EMBED_COPY,
  Name.TRACK_UPLOAD_OPEN,
  Name.TRACK_UPLOAD_START_UPLOADING,
  Name.TRACK_UPLOAD_COMPLETE_UPLOAD,
  Name.TWEET_FIRST_UPLOAD,
  Name.TRACK_UPLOAD_SUCCESS,
  Name.TRACK_UPLOAD_FAILURE,
  Name.TRACK_UPLOAD_USDC_GATED,
  Name.TRACK_UPLOAD_USDC_GATED_DOWNLOAD,
  Name.USDC_PURCHASE_GATED_TRACK_UNLOCKED,
  Name.USDC_PURCHASE_GATED_COLLECTION_UNLOCKED,
  Name.USDC_PURCHASE_GATED_DOWNLOAD_TRACK_UNLOCKED,
  Name.NOTIFICATIONS_OPEN,
  Name.NOTIFICATIONS_OPEN_PUSH_NOTIFICATION,
  Name.NOTIFICATIONS_CLICK_TILE,
  Name.NOTIFICATIONS_CLICK_MILESTONE_TWITTER_SHARE,
  Name.NOTIFICATIONS_CLICK_REMIX_CREATE_TWITTER_SHARE,
  Name.NOTIFICATIONS_CLICK_REMIX_COSIGN_TWITTER_SHARE,
  Name.NOTIFICATIONS_CLICK_DETHRONED_TWITTER_SHARE,
  Name.NOTIFICATIONS_CLICK_TRENDING_TRACK_TWITTER_SHARE,
  Name.NOTIFICATIONS_CLICK_TRENDING_UNDERGROUND_TWITTER_SHARE,
  Name.NOTIFICATIONS_CLICK_TASTEMAKER_TWITTER_SHARE,
  Name.NOTIFICATIONS_CLICK_ADD_TRACK_TO_PLAYLIST_TWITTER_SHARE,
  Name.NOTIFICATIONS_CLICK_USDC_PURCHASE_TWITTER_SHARE,
  Name.PLAYBACK_PLAY,
  Name.PLAYBACK_PAUSE,
  Name.PAGE_VIEW,
  Name.WEEKLY_ROTATION_BANNER_VIEW,
  Name.WEEKLY_ROTATION_BANNER_CLICK,
  Name.WEEKLY_ROTATION_PAGE_VIEW,
  Name.WEEKLY_ROTATION_PLAY_ALL,
  Name.SEND_AUDIO_SUCCESS,
  Name.SEND_AUDIO_FAILURE,
  Name.REWARDS_CLAIM_ALL_REQUEST,
  Name.REWARDS_CLAIM_ALL_SUCCESS,
  Name.BUY_USDC_ON_RAMP_OPENED,
  Name.BUY_USDC_ON_RAMP_CANCELED,
  Name.BUY_USDC_ON_RAMP_FAILURE,
  Name.BUY_USDC_ON_RAMP_SUCCESS,
  Name.BUY_USDC_SUCCESS,
  Name.BUY_USDC_FAILURE,
  Name.BUY_USDC_RECOVERY_IN_PROGRESS,
  Name.BUY_USDC_RECOVERY_SUCCESS,
  Name.BUY_USDC_RECOVERY_FAILURE,
  Name.BUY_USDC_ADD_FUNDS_MANUALLY,
  Name.BUY_SELL_SWAP_REQUESTED,
  Name.BUY_SELL_SWAP_CONFIRMED,
  Name.BUY_SELL_SWAP_SUCCESS,
  Name.BUY_SELL_SWAP_FAILURE,
  Name.BUY_SELL_ADD_FUNDS_CLICKED,
  Name.WITHDRAW_USDC_MODAL_OPENED,
  Name.WITHDRAW_USDC_ADDRESS_PASTED,
  Name.WITHDRAW_USDC_REQUESTED,
  Name.WITHDRAW_USDC_CREATE_DEST_TOKEN_ACCOUNT_START,
  Name.WITHDRAW_USDC_CREATE_DEST_TOKEN_ACCOUNT_SUCCESS,
  Name.WITHDRAW_USDC_CREATE_DEST_TOKEN_ACCOUNT_FAILED,
  Name.WITHDRAW_USDC_TRANSFER_TO_ROOT_WALLET,
  Name.WITHDRAW_USDC_COINFLOW_WITHDRAWAL_READY,
  Name.WITHDRAW_USDC_COINFLOW_SEND_TRANSACTION,
  Name.WITHDRAW_USDC_COINFLOW_SEND_TRANSACTION_FAILED,
  Name.WITHDRAW_USDC_CANCELLED,
  Name.WITHDRAW_USDC_FORM_ERROR,
  Name.WITHDRAW_USDC_SUCCESS,
  Name.WITHDRAW_USDC_FAILURE,
  Name.WITHDRAW_USDC_TRANSACTION_LINK_CLICKED,
  Name.STRIPE_SESSION_CREATION_ERROR,
  Name.STRIPE_SESSION_CREATED,
  Name.STRIPE_MODAL_INITIALIZED,
  Name.STRIPE_REQUIRES_PAYMENT,
  Name.STRIPE_FULLFILMENT_PROCESSING,
  Name.STRIPE_FULLFILMENT_COMPLETE,
  Name.STRIPE_ERROR,
  Name.STRIPE_REJECTED,
  Name.PURCHASE_CONTENT_BUY_CLICKED,
  Name.PURCHASE_CONTENT_STARTED,
  Name.PURCHASE_CONTENT_SUCCESS,
  Name.PURCHASE_CONTENT_FAILURE,
  Name.PURCHASE_CONTENT_TWITTER_SHARE,
  Name.PURCHASE_CONTENT_TOS_CLICKED,
  Name.PURCHASE_CONTENT_USDC_USER_BANK_COPIED,
  Name.CHAT_BLAST_MESSAGE_SENT,
  Name.SEND_MESSAGE_SUCCESS,
  // The only record of a chat abuse report
  Name.CHAT_REPORT_USER,
  Name.COMMENTS_NOTIFICATION_OPEN,
  Name.LAUNCHPAD_SPLASH_GET_STARTED,
  Name.LAUNCHPAD_HAS_EXISTING_FAN_CLUB,
  Name.LAUNCHPAD_SPLASH_LEARN_MORE_CLICKED,
  Name.LAUNCHPAD_WALLET_CONNECT_SUCCESS,
  Name.LAUNCHPAD_WALLET_CONNECT_ERROR,
  Name.LAUNCHPAD_WALLET_INSUFFICIENT_BALANCE,
  Name.LAUNCHPAD_SETUP_CONTINUE,
  Name.LAUNCHPAD_FORM_BACK,
  Name.LAUNCHPAD_FORM_INPUT_CHANGE,
  Name.LAUNCHPAD_REVIEW_CONTINUE,
  Name.LAUNCHPAD_COIN_CREATION_STARTED,
  Name.LAUNCHPAD_COIN_CREATION_SUCCESS,
  Name.LAUNCHPAD_COIN_CREATION_FAILURE,
  Name.LAUNCHPAD_FIRST_BUY_RETRY,
  Name.LAUNCHPAD_FIRST_BUY_MAX_BUTTON,
  Name.LAUNCHPAD_FIRST_BUY_QUOTE_RECEIVED,
  Name.LAUNCHPAD_BUY_MODAL_OPEN,
  Name.LAUNCHPAD_BUY_MODAL_CLOSE,
  Name.LAUNCHPAD_BUY_MODAL_SUBMIT,
  Name.LAUNCHPAD_BUY_MODAL_SUCCESS,
  Name.LAUNCHPAD_BUY_MODAL_FAILURE,
  Name.LAUNCHPAD_BUY_MODAL_CHANGE_CURRENCY,
  Name.LAUNCHPAD_BUY_MODAL_FORM_CHANGE,
  Name.LAUNCHPAD_BUY_MODAL_MAX_BUTTON,
  Name.LAUNCHPAD_BUY_MODAL_CONTINUE,
  Name.LAUNCHPAD_BUY_MODAL_BACK,
  Name.LAUNCHPAD_CLAIM_FEES_CLICKED,
  Name.LAUNCHPAD_CLAIM_FEES_SUCCESS,
  Name.LAUNCHPAD_CLAIM_FEES_FAILURE,
  Name.LAUNCHPAD_CLAIM_FEES_CONNECT_WALLET,
  Name.LAUNCHPAD_CLAIM_FEES_SWITCH_WALLET,
  Name.LAUNCHPAD_CLAIM_VESTED_COINS_SWITCH_WALLET,
  Name.LAUNCHPAD_CLAIM_VESTED_COINS_CLICKED,
  Name.LAUNCHPAD_CLAIM_VESTED_COINS_CONNECT_WALLET,
  Name.LAUNCHPAD_CLAIM_FEES_WALLET_CONNECTED,
  Name.LAUNCHPAD_CLAIM_VESTED_COINS_WALLET_CONNECTED,
  Name.LAUNCHPAD_CLAIM_VESTED_COINS_SUCCESS,
  Name.LAUNCHPAD_CLAIM_VESTED_COINS_FAILURE
])

/** Share of devices that send non-core events */
export const ANALYTICS_SAMPLE_RATE = 0.1

// FNV-1a, so a device lands in the same bucket on every load and platform
const hashString = (value: string) => {
  let hash = 0x811c9dc5
  for (let i = 0; i < value.length; i++) {
    hash ^= value.charCodeAt(i)
    hash = Math.imul(hash, 0x01000193)
  }
  return hash >>> 0
}

export const isCoreAnalyticsEvent = (
  eventName: string,
  coreEvents: ReadonlySet<string> = CORE_ANALYTICS_EVENTS
) =>
  coreEvents.has(eventName) ||
  // Weekly Rotation events are still being added
  eventName.startsWith('Weekly Rotation')

/**
 * Returns null when this device should not send the event, otherwise the
 * sample rate it was sent at (1 for core events). Non-core events carry the
 * rate as a `sampleRate` property so counts can be scaled back up.
 */
export const getAnalyticsSampleRate = (
  eventName: string,
  deviceId: string | undefined,
  coreEvents: ReadonlySet<string> = CORE_ANALYTICS_EVENTS
) => {
  if (isCoreAnalyticsEvent(eventName, coreEvents) || !deviceId) return 1
  const bucket = hashString(deviceId) % 10000
  return bucket < ANALYTICS_SAMPLE_RATE * 10000 ? ANALYTICS_SAMPLE_RATE : null
}
